networks:
  traefik:
    external: true

services:
  revalidator:
    container_name: alexjportfolio-revalidator
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - path: ./.env
        required: true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revalidator.service=revalidator"
      - "traefik.http.routers.revalidator.rule=Host(`revalidator.home.alexanderjalexander.com`)"
      - "traefik.http.routers.revalidator.entrypoints=websecure"
      - "traefik.http.routers.revalidator.tls=true"
      - "traefik.http.routers.revalidator.tls.certResolver=cloudflare"
      - "traefik.http.services.revalidator.loadbalancer.server.port=4000"
