services:
  revalidator:
    build: .
    restart: unless-stopped
    container_name: portfolio-revalidator
    ports:
      - "4000:4000"
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s